#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

mkdir -p "$HOME/.local/bin"

echo
echo "You might want to do some of these things first before proceeding:"
echo " - Build and install Neovim: https://github.com/neovim/neovim/blob/master/BUILD.md"
echo " - Install wezterm: https://wezterm.org/install/linux.html"
echo

read -p "Done? Proceed? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo
else
    exit 0
fi

read -p "Install basic software? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo apt install git wget unzip
fi

read -p "Install apt-listbugs and apt-listchanges? (especially on testing/unstable) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo apt install apt-listbugs apt-listchanges
fi

read -p "Install zoxide? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo apt install zoxide
fi

read -p "Install redshift-gtk and config? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo apt install redshift-gtk
    tee "$HOME/.config/redshift.conf" >/dev/null <<EOF
[redshift]
temp-day=6500
temp-night=4000
transition=0
dawn-time=07:00
dusk-time=22:30
EOF
    echo "NOTE: Enable autostart by starting redshift and choosing the option in the menu."
fi

read -p "Install walk (and Go as dependency)? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo apt install golang
    go install github.com/antonmedv/walk@latest
    ln -s "$HOME/go/bin/walk" "$HOME/.local/bin/walk"
fi

read -p "Install fonts? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo apt install fonts-noto-core

    mkdir /tmp/JetBrainsMonoNerd
    wget 'https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip' -O /tmp/JetBrainsMonoNerd/JetBrainsMono.zip
    pushd /tmp/JetBrainsMonoNerd
    unzip JetBrainsMono.zip
    sudo mkdir -p /usr/share/fonts/truetype/JetBrainsMonoNerd
    sudo cp /tmp/JetBrainsMonoNerd/*.ttf /usr/share/fonts/truetype/JetBrainsMonoNerd/
    popd
    sudo rm -rf /tmp/JetBrainsMonoNerd
    sudo fc-cache -f
fi

read -p "Install Neovim configs? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp -r "$SCRIPT_DIR/.config/nvim" "$HOME/.config/"

    read -p "Setup Neovim as default editor (update-alternatives)? " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        sudo "$HOME/.config/nvim/setup-nvim-as-default-editor"
    fi
fi

read -p "Install basic Vim config? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp "$SCRIPT_DIR/.vimrc" "$HOME/.vimrc"
fi

read -p "Install basic tmux config? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp -r "$SCRIPT_DIR/.config/tmux" "$HOME/.config/"
fi

read -p "Install alacritty configs? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp -r "$SCRIPT_DIR/.config/alacritty" "$HOME/.config/"
fi

read -p "Install wezterm configs? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp -r "$SCRIPT_DIR/.wezterm.lua" "$HOME/.wezterm.lua"
fi

read -p "Install bashrc? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp -r "$SCRIPT_DIR/.bashrc" "$HOME/.bashrc"
fi

read -p "Install bash powerline? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp -r "$SCRIPT_DIR/.bash-powerline.sh" "$HOME/.bash-powerline.sh"
fi

read -p "Install xfce configs? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp -r "$SCRIPT_DIR/.config/xfce4" "$HOME/.config/"
fi

read -p "Replace global gitconfig and gitignore settings? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp "$SCRIPT_DIR/gitconfig" "$HOME/.gitconfig"
    cp "$SCRIPT_DIR/gitignore" "$HOME/.gitignore"
fi

read -p "Install zswap enabling script and systemd service? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo cp "$SCRIPT_DIR/enable-zswap.sh" "/usr/local/bin/"
    sudo cp "$SCRIPT_DIR/enable-zswap.service" "/etc/systemd/system/"
    sudo systemctl daemon-reload
    sudo systemctl --now enable enable-zswap.service
fi

read -p "Show user list in lightdm login greeter? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo sed -i 's/#greeter-hide-users=false/greeter-hide-users=false/' "/etc/lightdm/lightdm.conf"
fi

read -p "Install SpeedCrunch config? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp -r "$SCRIPT_DIR/.config/SpeedCrunch" "$HOME/.config/"
    echo "Install SpeedCrunch: https://heldercorreia.bitbucket.io/speedcrunch/download.html"
fi

echo
echo "More nice things to remember:"
echo " - Install Simple-Adw-Dark cursors from https://gitlab.com/cursors/simp1e"
echo " - If mouse cursor is HUGE, go to Mouse Settings and change cursor size to something else"
echo "   than 16, and then back to 16."
echo " - Install papirus icon theme (sudo apt install papirus-icon-theme)"
